export { default as ImageSlider } from './ImageSlider'
export { default as EditorialText } from './EditorialText'
export { default as MarketingSale } from './MarketingSale'
export { default as MarketingTwo } from './MarketingTwo'
export { default as MarketingThree } from './MarketingThree'
export { default as MarketingOne } from './MarketingOne'